### ISSUE TITLE
Solidus needs a login parameter?

### ISSUE THREAD

**Issue by sourcesolver** [solidusio-contrib/solidus_stripe#116]
I'm getting this error when I go to test a payment:

I, [2021-11-29T09:19:19.656205 #19393] INFO -- : [39855e67-587e-4ebe-8f22-143f843806a1] Started PATCH"/checkout/update/payment" for 24.228.203.152 at 2021-11-29 09:19:19 +0100 
I, [2021-11-29T09:19:19.658170 #19393] INFO -- : [39855e67-587e-4ebe-8f22-143f843806a1] Proce
ssing by Spree::CheckoutController#update as HTML 
I, [2021-11-29T09:19:19.658416 #19393] INFO -- : [39855e67-587e-4ebe-8f22-143f843806a1]  Par
ameters: {"authenticity_token"=>"[FILTERED]", "order"=>{"payments_attributes"=>[{"payment_meth
od_id"=>"4"}]}, "payment_source"=>{"2"=>{"name"=>"REDACTED", "number"=>"[FILTERED]", "expir
y"=>"", "verification_value"=>"[FILTERED]", "address_attributes"=>{"name"=>"REDACTED", "com
pany"=>"", "address1"=>"REDATED", "address2"=>"", "city"=>"REDACTED", "country_id"=
>"REDACTED", "state_id"=>"REDACTED", "state_name"=>"", "zipcode"=>"REDACTED", "phone"=>"", "alternative_ph
one"=>""}, "cc_type"=>""}, "4"=>{"name"=>"REDACTED", "number"=>"[FILTERED]", "expiry"=>"6/29", "verification_value"=>"[FILTERED]", "address_attributes"=>{"name"=>"REDACTED", "comp
any"=>"", "address1"=>"REDACTED", "address2"=>"", "city"=>"REDACTED", "country_id"=>
"REDACTED", "state_id"=>"REDACTED", "state_name"=>"", "zipcode"=>"REDACTED", "phone"=>"", "alternative_pho
ne"=>""}, "cc_type"=>"visa"}}, "state"=>"payment"} 
I, [2021-11-29T09:19:19.778745 #19393] INFO -- : [39855e67-587e-4ebe-8f22-143f843806a1] Compl
eted 500 Internal Server Error in 120ms (ActiveRecord: 47.5ms | Allocations: 38329) 
F, [2021-11-29T09:19:19.780714 #19393] FATAL -- : [39855e67-587e-4ebe-8f22-143f843806a1] 
[39855e67-587e-4ebe-8f22-143f843806a1] ArgumentError (Missing required parameter: login): 
[39855e67-587e-4ebe-8f22-143f843806a1] 
[39855e67-587e-4ebe-8f22-143f843806a1] activemerchant (1.124.0) lib/active_merchant/billing/ga
teway.rb:325:in `block in requires!'

What login parameter?!

bundle install
.
.
.
Using solidus_square 0.0.1
.
.
.
Bundle complete! 23 Gemfile dependencies, 152 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
bundle info solidus_square
* solidus_square (0.0.1)
Summary: Solidus extension for using Square in your store.
Homepage: https://github.com/nebulab/solidus_square#readme
Source Code: https://github.com/nebulab/solidus_square
Changelog: https://github.com/nebulab/solidus_square/blob/master/CHANGELOG.md
Path: /usr/local/rvm/gems/ruby-2.6.1/gems/solidus_square-0.0.1
rails generate solidus_square:install
/usr/share/solidus/REDACTED/config/initializers/solidus_square.rb:2:in `<main>': uninitialized constant SolidusSquare (NameError)
head --lines=2 /usr/share/solidus/REDACTED/config/initializers/solidus_square.rb
# config/initializers/solidus_square.rb
SolidusSquare.configure do |config|

**Comment by sourcesolver** [comment]
![tumbleweed](https://user-images.githubusercontent.com/80441845/146701082-408ea683-1d84-42c8-9f4f-1e52b27cc6e6.gif)

**Comment by elia** [comment]
I'm cleaning up the repo, closing all v4 related issues and PRs. If you think it should stay open just ping me and I'll reopen.
Thanks for participating and reporting issues! 🙏
